#!flask/bin/python
import datetime, random
from app import app, models, db
from app.models import User, Item

# Buildup
# - Users
user_list = [] 
zip_dict = {
    0: {"zipcode":80920, "lat":38.957598, "lng":-104.770770},
    1: {"zipcode":80918, "lat":38.910393, "lng":-104.780362},
    2: {"zipcode":80907, "lat":38.878231, "lng":-104.827015},
    3: {"zipcode":80904, "lat":38.860829, "lng":-104.876163},
    4: {"zipcode":80905, "lat":38.818910, "lng":-104.838348},
    5: {"zipcode":80903, "lat":38.831526, "lng":-104.815062},
    6: {"zipcode":80909, "lat":38.853475, "lng":-104.775218},
    7: {"zipcode":80910, "lat":38.812066, "lng":-104.774580},
    8: {"zipcode":80915, "lat":38.849797, "lng":-104.717043},
    9: {"zipcode":80914, "lat":38.824001, "lng":-104.704184} 
}

for i in range(0, 10):
    user = User("User"+str(i), "user"+str(i)+"@email.com", "user"+str(i))
    user.zipcode = zip_dict[i]["zipcode"]
    user.lat = zip_dict[i]["lat"]
    user.lng = zip_dict[i]["lng"]
    user_list.append(user)
    db.session.add(user)
    db.session.commit()

# - Items
item_dict = {
    0: {"title":"Eggs Are Good",
        "category":"Protein",
        "price":".15",
        "price_type":"each",
        "description":"Some good eggs here, folks",
        "post_date":datetime.datetime(2016, 1, 1, 13, 00),
        "user_id":random.randint(1,10) },
    1: {"title":"Large Eggs",
        "category":"Protein",
        "price":".20",
        "price_type":"each",
        "description":"Some large eggs here, folks",
        "post_date":datetime.datetime(2016, 1, 1, 14, 00),
        "user_id":random.randint(1,10) },
    2: {"title":"Eggs by the Dozen",
        "category":"Protein",
        "price":"1.00",
        "price_type":"total",
        "description":"Lots of eggs here, folks",
        "post_date":datetime.datetime(2016, 1, 1, 15, 00),
        "user_id":random.randint(1,10) },
    3: {"title":"Chicken Breasts",
        "category":"Protein",
        "price":"1.00",
        "price_type":"each",
        "description":"Yummy",
        "post_date":datetime.datetime(2016, 1, 2, 13, 00),
        "user_id":random.randint(1,10) },
    4: {"title":"Whole Chicken",
        "category":"Protein",
        "price":"5.00",
        "price_type":"total",
        "description":"Plucked and prepared",
        "post_date":datetime.datetime(2016, 1, 2, 13, 00),
        "user_id":random.randint(1,10) },
    5: {"title":"Brown Eggs",
        "category":"Protein",
        "price":".15",
        "price_type":"each",
        "description":"Some brown eggs here, folks",
        "post_date":datetime.datetime(2016, 1, 3, 13, 00),
        "user_id":random.randint(1,10) },
    6: {"title":"Eggs",
        "category":"Protein",
        "price":".10",
        "price_type":"each",
        "description":"Some eggs here, folks",
        "post_date":datetime.datetime(2016, 1, 3, 15, 00),
        "user_id":random.randint(1,10) },
    7: {"title":"Eggs Eggs Eggs",
        "category":"Protein",
        "price":".7",
        "price_type":"each",
        "description":"Many good eggs here, folks",
        "post_date":datetime.datetime(2016, 1, 5, 13, 00),
        "user_id":random.randint(1,10) },
    8: {"title":"Pork Shoulder",
        "category":"Protein",
        "price":"5.50",
        "price_type":"total",
        "description":"Fresh from the farm.",
        "post_date":datetime.datetime(2016, 1, 5, 8, 00),
        "user_id":random.randint(1,10) },
    9: {"title":"Beef Tenderloin",
        "category":"Protein",
        "price":"4.00",
        "price_type":"each",
        "description":"Yummy yummy",
        "post_date":datetime.datetime(2016, 1, 6, 1, 00),
        "user_id":random.randint(1,10) },
    10: {"title":"Chicken Breasts",
        "category":"Protein",
        "price":"2.00",
        "price_type":"each",
        "description":"Very tender.",
        "post_date":datetime.datetime(2016, 1, 6, 2, 00),
        "user_id":random.randint(1,10) },
    11: {"title":"Whole Chicken",
        "category":"Protein",
        "price":"5.00",
        "price_type":"each",
        "description":"I had too many.",
        "post_date":datetime.datetime(2016, 1, 6, 3, 00),
        "user_id":random.randint(1,10) },
    12: {"title":"Sausage Links",
        "category":"Protein",
        "price":".50",
        "price_type":"each",
        "description":"Homegrown weenies.",
        "post_date":datetime.datetime(2016, 1, 6, 4, 00),
        "user_id":random.randint(1,10) },
    13: {"title":"Duck Eggs",
        "category":"Protein",
        "price":".25",
        "price_type":"each",
        "description":"Some huge eggs here, folks",
        "post_date":datetime.datetime(2016, 1, 6, 5, 00),
        "user_id":random.randint(1,10) },
    14: {"title":"Eggs Are White",
        "category":"Protein",
        "price":".12",
        "price_type":"each",
        "description":"Some white eggs here, folks",
        "post_date":datetime.datetime(2016, 1, 6, 5, 30),
        "user_id":random.randint(1,10) },
    15: {"title":"Whole Carrots",
        "category":"Vegetable",
        "price":".10",
        "price_type":"each",
        "description":"They are orange. Ish. Mostly.",
        "post_date":datetime.datetime(2016, 1, 6, 6, 00),
        "user_id":random.randint(1,10) },
    16: {"title":"Broccoli /lb",
        "category":"Vegetable",
        "price":"1.15",
        "price_type":"each",
        "description":"Nice fresh brocles.",
        "post_date":datetime.datetime(2016, 1, 6, 6, 00),
        "user_id":random.randint(1,10) },
    17: {"title":"Cabbage",
        "category":"Vegetable",
        "price":".95",
        "price_type":"each",
        "description":"Crunchy and delicious.",
        "post_date":datetime.datetime(2016, 1, 6, 7, 00),
        "user_id":random.randint(1,10) },
    18: {"title":"Red Onion",
        "category":"Vegetable",
        "price":".15",
        "price_type":"each",
        "description":"More like burgundy..",
        "post_date":datetime.datetime(2016, 1, 6, 8, 00),
        "user_id":random.randint(1,10) },
    19: {"title":"Yellow Onions by the Pound",
        "category":"Vegetable",
        "price":"1.65",
        "price_type":"each",
        "description":"Very good flavor.",
        "post_date":datetime.datetime(2016, 1, 6, 13, 00),
        "user_id":random.randint(1,10) },
    20: {"title":"Other Onions",
        "category":"Vegetable",
        "price":".15",
        "price_type":"each",
        "description":"How many kinds of onion are there??",
        "post_date":datetime.datetime(2016, 1, 1, 13, 00),
        "user_id":random.randint(1,10) },
    21: {"title":"Too Many Onions",
        "category":"Vegetable",
        "price":".25",
        "price_type":"each",
        "description":"Maybe I should sell something other than onions.",
        "post_date":datetime.datetime(2016, 1, 1, 13, 00),
        "user_id":random.randint(1,10) },
    22: {"title":"Potatoes",
        "category":"Vegetable",
        "price":"1.00",
        "price_type":"each",
        "description":"Starchy",
        "post_date":datetime.datetime(2016, 1, 1, 13, 00),
        "user_id":random.randint(1,10) },
    23: {"title":"Red Potatoes",
        "category":"Vegetable",
        "price":".50",
        "price_type":"each",
        "description":"Oh, here we go with the colors again..",
        "post_date":datetime.datetime(2016, 1, 1, 13, 00),
        "user_id":random.randint(1,10) },
    24: {"title":"Rooster Potatoes by the Pound",
        "category":"Vegetable",
        "price":"3.00",
        "price_type":"each",
        "description":"Way to mix it up.",
        "post_date":datetime.datetime(2016, 1, 1, 13, 00),
        "user_id":random.randint(1,10) } }

for i in range(0, 25):
    item = Item(item_dict[i]["title"], item_dict[i]["category"], \
        item_dict[i]["price"], item_dict[i]["price_type"], \
        item_dict[i]["description"], item_dict[i]["user_id"])
    item.post_date = item_dict[i]["post_date"]
    db.session.add(item)
    db.session.commit()



"""        
    25: {"title" = "Eggs Are Good",
        "category" = "Protein",
        "price" = ".15",
        "price_type" = "each",
        "description" = "Some good eggs here, folks",
        "post_date" = datetime.datetime(2016, 1, 1, 13, 00),
        "user_id" = random.randint(0,9) },
    26: {"title" = "Eggs Are Good",
        "category" = "Protein",
        "price" = ".15",
        "price_type" = "each",
        "description" = "Some good eggs here, folks",
        "post_date" = datetime.datetime(2016, 1, 1, 13, 00),
        "user_id" = random.randint(0,9) },
    27: {"title" = "Eggs Are Good",
        "category" = "Protein",
        "price" = ".15",
        "price_type" = "each",
        "description" = "Some good eggs here, folks",
        "post_date" = datetime.datetime(2016, 1, 1, 13, 00),
        "user_id" = random.randint(0,9) },
    28: {"title" = "Eggs Are Good",
        "category" = "Protein",
        "price" = ".15",
        "price_type" = "each",
        "description" = "Some good eggs here, folks",
        "post_date" = datetime.datetime(2016, 1, 1, 13, 00),
        "user_id" = random.randint(0,9) },
    29: {"title" = "Eggs Are Good",
        "category" = "Protein",
        "price" = ".15",
        "price_type" = "each",
        "description" = "Some good eggs here, folks",
        "post_date" = datetime.datetime(2016, 1, 1, 13, 00),
        "user_id" = random.randint(0,9) },
    30: {"title" = "Eggs Are Good",
        "category" = "Protein",
        "price" = ".15",
        "price_type" = "each",
        "description" = "Some good eggs here, folks",
        "post_date" = datetime.datetime(2016, 1, 1, 13, 00),
        "user_id" = random.randint(0,9) },
    31: {"title" = "Eggs Are Good",
        "category" = "Protein",
        "price" = ".15",
        "price_type" = "each",
        "description" = "Some good eggs here, folks",
        "post_date" = datetime.datetime(2016, 1, 1, 13, 00),
        "user_id" = random.randint(0,9) },
    32: {"title" = "Eggs Are Good",
        "category" = "Protein",
        "price" = ".15",
        "price_type" = "each",
        "description" = "Some good eggs here, folks",
        "post_date" = datetime.datetime(2016, 1, 1, 13, 00),
        "user_id" = random.randint(0,9) },
    33: {"title" = "Eggs Are Good",
        "category" = "Protein",
        "price" = ".15",
        "price_type" = "each",
        "description" = "Some good eggs here, folks",
        "post_date" = datetime.datetime(2016, 1, 1, 13, 00),
        "user_id" = random.randint(0,9) },
    34: {"title" = "Eggs Are Good",
        "category" = "Protein",
        "price" = ".15",
        "price_type" = "each",
        "description" = "Some good eggs here, folks",
        "post_date" = datetime.datetime(2016, 1, 1, 13, 00),
        "user_id" = random.randint(0,9) },
    35: {"title" = "Eggs Are Good",
        "category" = "Protein",
        "price" = ".15",
        "price_type" = "each",
        "description" = "Some good eggs here, folks",
        "post_date" = datetime.datetime(2016, 1, 1, 13, 00),
        "user_id" = random.randint(0,9) },
    36: {"title" = "Eggs Are Good",
        "category" = "Protein",
        "price" = ".15",
        "price_type" = "each",
        "description" = "Some good eggs here, folks",
        "post_date" = datetime.datetime(2016, 1, 1, 13, 00),
        "user_id" = random.randint(0,9) },
    37: {"title" = "Eggs Are Good",
        "category" = "Protein",
        "price" = ".15",
        "price_type" = "each",
        "description" = "Some good eggs here, folks",
        "post_date" = datetime.datetime(2016, 1, 1, 13, 00),
        "user_id" = random.randint(0,9) },
    38: {"title" = "Eggs Are Good",
        "category" = "Protein",
        "price" = ".15",
        "price_type" = "each",
        "description" = "Some good eggs here, folks",
        "post_date" = datetime.datetime(2016, 1, 1, 13, 00),
        "user_id" = random.randint(0,9) },
    39: {"title" = "Eggs Are Good",
        "category" = "Protein",
        "price" = ".15",
        "price_type" = "each",
        "description" = "Some good eggs here, folks",
        "post_date" = datetime.datetime(2016, 1, 1, 13, 00),
        "user_id" = random.randint(0,9) },
    40: {"title" = "Eggs Are Good",
        "category" = "Protein",
        "price" = ".15",
        "price_type" = "each",
        "description" = "Some good eggs here, folks",
        "post_date" = datetime.datetime(2016, 1, 1, 13, 00),
        "user_id" = random.randint(0,9) },
    41: {"title" = "Eggs Are Good",
        "category" = "Protein",
        "price" = ".15",
        "price_type" = "each",
        "description" = "Some good eggs here, folks",
        "post_date" = datetime.datetime(2016, 1, 1, 13, 00),
        "user_id" = random.randint(0,9) },
    42: {"title" = "Eggs Are Good",
        "category" = "Protein",
        "price" = ".15",
        "price_type" = "each",
        "description" = "Some good eggs here, folks",
        "post_date" = datetime.datetime(2016, 1, 1, 13, 00),
        "user_id" = random.randint(0,9) },
    43: {"title" = "Eggs Are Good",
        "category" = "Protein",
        "price" = ".15",
        "price_type" = "each",
        "description" = "Some good eggs here, folks",
        "post_date" = datetime.datetime(2016, 1, 1, 13, 00),
        "user_id" = random.randint(0,9) },
    44: {"title" = "Eggs Are Good",
        "category" = "Protein",
        "price" = ".15",
        "price_type" = "each",
        "description" = "Some good eggs here, folks",
        "post_date" = datetime.datetime(2016, 1, 1, 13, 00),
        "user_id" = random.randint(0,9) },
    45: {"title" = "Eggs Are Good",
        "category" = "Protein",
        "price" = ".15",
        "price_type" = "each",
        "description" = "Some good eggs here, folks",
        "post_date" = datetime.datetime(2016, 1, 1, 13, 00),
        "user_id" = random.randint(0,9) },
    46: {"title" = "Eggs Are Good",
        "category" = "Protein",
        "price" = ".15",
        "price_type" = "each",
        "description" = "Some good eggs here, folks",
        "post_date" = datetime.datetime(2016, 1, 1, 13, 00),
        "user_id" = random.randint(0,9) },
    47: {"title" = "Eggs Are Good",
        "category" = "Protein",
        "price" = ".15",
        "price_type" = "each",
        "description" = "Some good eggs here, folks",
        "post_date" = datetime.datetime(2016, 1, 1, 13, 00),
        "user_id" = random.randint(0,9) },
    48: {"title" = "Eggs Are Good",
        "category" = "Protein",
        "price" = ".15",
        "price_type" = "each",
        "description" = "Some good eggs here, folks",
        "post_date" = datetime.datetime(2016, 1, 1, 13, 00),
        "user_id" = random.randint(0,9) },
    49: {"title" = "Eggs Are Good",
        "category" = "Protein",
        "price" = ".15",
        "price_type" = "each",
        "description" = "Some good eggs here, folks",
        "post_date" = datetime.datetime(2016, 1, 1, 13, 00),
        "user_id" = random.randint(0,9) } }
"""
